apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ksfa1r5yv-go-gitops
  description: This is GitOps manifest for ksfa1r5yv-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ksfa1r5yv-go
    backstage.io/kubernetes-id: ksfa1r5yv-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: ksfa1r5yv-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ksfa1r5yv-go
