apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ksfa1r5yv-go
  janus-idp.io/tekton: ksfa1r5yv-go
  backstage.io/kubernetes-id: ksfa1r5yv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ksfa1r5yv-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
