apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ksfa1r5yv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ksfa1r5yv-go 
  name: ksfa1r5yv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ksfa1r5yv-go 
